"""
Deterministic HPI renderer.

Takes a schema-validated HPIDraft dict and emits clinical prose via
templates. The renderer is PURE CODE — it cannot invent content,
introduce contradictions, hallucinate values, mismatch pronouns, or
write meta-commentary, because every output sentence is generated by
a function that reads only the validated input.

Renderer guarantees:
  - Every PSA value comes verbatim from draft.psa_trajectory
  - Every treatment claim comes verbatim from draft.treatment_history
  - Sex pronouns derived from draft.intro.sex (deterministic mapping)
  - No "I have followed the rules" / meta-commentary possible
  - No name placeholders (uses draft.intro.name)
  - No mid-sentence truncations (every render fn returns complete sentence)
"""
from __future__ import annotations

from typing import Dict, List, Optional, Any


# ---------------------------------------------------------------------------
# Pronoun mapping
# ---------------------------------------------------------------------------

_PRONOUNS = {
    "male":   {"sub": "he",  "obj": "him", "poss": "his",  "self": "himself"},
    "female": {"sub": "she", "obj": "her", "poss": "her",  "self": "herself"},
}


def _pron(sex: str) -> Dict[str, str]:
    return _PRONOUNS.get(sex, {"sub": "the patient",
                               "obj": "the patient",
                               "poss": "the patient's",
                               "self": "themselves"})


# ---------------------------------------------------------------------------
# Date formatter
# ---------------------------------------------------------------------------

_MONTH_NAMES = ["", "January", "February", "March", "April", "May",
                "June", "July", "August", "September", "October",
                "November", "December"]


def _format_date(date_str: Optional[str]) -> str:
    """Render YYYY-MM-DD / YYYY-MM / YYYY as 'Month DD, YYYY' / 'Month YYYY' / 'YYYY'."""
    if not date_str:
        return ""
    parts = date_str.split("-")
    try:
        if len(parts) == 1:
            return parts[0]
        if len(parts) == 2:
            return f"{_MONTH_NAMES[int(parts[1])]} {parts[0]}"
        if len(parts) == 3:
            return f"{_MONTH_NAMES[int(parts[1])]} {int(parts[2])}, {parts[0]}"
    except (ValueError, IndexError):
        return date_str
    return date_str


# ---------------------------------------------------------------------------
# Treatment modality display labels
# ---------------------------------------------------------------------------

_MODALITY_DISPLAY = {
    "prostatectomy": "radical prostatectomy",
    "radiation": "radiation therapy",
    "brachytherapy": "brachytherapy",
    "focal-therapy": "focal therapy",
    "active-surveillance": "active surveillance",
    "ADT": "androgen deprivation therapy",
    "chemotherapy": "chemotherapy",
    "immunotherapy": "immunotherapy",
    "TURP": "TURP",
    "TURBT": "TURBT",
    "nephrectomy": "nephrectomy",
    "cystectomy": "cystectomy",
    "ureteroscopy": "ureteroscopy",
    "shock-wave-lithotripsy": "shock wave lithotripsy",
    "PCNL": "percutaneous nephrolithotomy",
    "orchiectomy": "orchiectomy",
    "varicocelectomy": "varicocelectomy",
    "hydrocelectomy": "hydrocelectomy",
    "cystoscopy-with-treatment": "cystoscopy with treatment",
}

_STATUS_VERB = {
    "completed":   "completed",
    "ongoing":     "is currently undergoing",
    "discontinued": "discontinued",
    "declined":    "declined",
    "scheduled":   "is scheduled for",
}

_PROCEDURE_DISPLAY = {
    "biopsy": "biopsy",
    "cystoscopy": "cystoscopy",
    "urodynamics": "urodynamic study",
    "mri": "MRI",
    "ct": "CT",
    "ultrasound": "ultrasound",
    "psma-pet": "PSMA PET",
    "bone-scan": "bone scan",
    "dexa": "DEXA scan",
    "iv-pyelogram": "IV pyelogram",
    "retrograde-pyelogram": "retrograde pyelogram",
    "voiding-cystogram": "voiding cystogram",
}


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------

def render_intro(intro: Optional[Dict]) -> str:
    """First sentence: '{Name} is a {age}-year-old {sex} who returns for {reason}.'"""
    if not intro:
        return ""
    visit_verb = {
        "follow-up": "returns for",
        "consult": "presents for urology consultation for",
        "new-patient": "is a new urology patient seen for",
        "post-op": "returns for post-operative follow-up of",
        "pre-op": "is seen for pre-operative evaluation of",
    }.get(intro.get("visit_type", "follow-up"), "returns for")
    return (
        f"{intro['name']} is a {intro['age']}-year-old "
        f"{intro['sex']} who {visit_verb} {intro['visit_reason']}."
    )


def render_prior_diagnosis(dx: Optional[Dict], sex: str) -> str:
    """'He was diagnosed with X in YYYY (Gleason 3+3, Grade Group 1).'"""
    if not dx or not dx.get("primary_dx"):
        return ""
    p = _pron(sex)
    parts = [f"{p['sub'].capitalize()} was diagnosed with {dx['primary_dx']}"]
    if dx.get("dx_date"):
        parts.append(f"in {_format_date(dx['dx_date'])}")
    qualifier_parts = []
    if dx.get("gleason"):
        gg = dx.get("grade_group")
        if gg:
            qualifier_parts.append(f"Gleason {dx['gleason']}, Grade Group {gg}")
        else:
            qualifier_parts.append(f"Gleason {dx['gleason']}")
    elif dx.get("grade_group"):
        qualifier_parts.append(f"Grade Group {dx['grade_group']}")
    if dx.get("risk_category"):
        qualifier_parts.append(f"{dx['risk_category']} risk")
    if qualifier_parts:
        parts.append(f"({'; '.join(qualifier_parts)})")
    return " ".join(parts) + "."


def render_treatment_history(events: Optional[List[Dict]], sex: str) -> str:
    """Chronological list of treatment events. One sentence per event."""
    if not events:
        return ""
    p = _pron(sex)
    sentences: List[str] = []
    # Sort by date if available (oldest first for chronology)
    def _date_key(e):
        return e.get("date") or "9999"
    sorted_events = sorted(events, key=_date_key)
    for evt in sorted_events:
        modality_label = _MODALITY_DISPLAY.get(evt["modality"], evt["modality"])
        status_verb = _STATUS_VERB.get(evt["status"], evt["status"])
        date_part = ""
        if evt.get("date"):
            date_part = f" in {_format_date(evt['date'])}"
        if evt["status"] == "completed":
            sentence = f"{p['sub'].capitalize()} completed {modality_label}{date_part}."
        elif evt["status"] == "ongoing":
            if evt["modality"] == "active-surveillance":
                sentence = (f"{p['sub'].capitalize()} has been managed with "
                            f"active surveillance{date_part}.")
            else:
                if date_part:
                    started_part = f" started{date_part}"
                else:
                    started_part = ""
                sentence = (f"{p['sub'].capitalize()} {status_verb} "
                            f"{modality_label}{started_part}.")
        elif evt["status"] == "discontinued":
            sentence = (f"{p['sub'].capitalize()} previously received "
                        f"{modality_label}{date_part}, since discontinued.")
        elif evt["status"] == "declined":
            sentence = f"{p['sub'].capitalize()} declined {modality_label}."
        elif evt["status"] == "scheduled":
            sentence = (f"{p['sub'].capitalize()} {status_verb} "
                        f"{modality_label}{date_part}.")
        else:
            sentence = (f"{p['sub'].capitalize()} {status_verb} "
                        f"{modality_label}{date_part}.")
        # Append optional narrative note
        if evt.get("narrative_note"):
            sentence = sentence.rstrip(".") + f" — {evt['narrative_note']}."
        sentences.append(sentence)
    return " ".join(sentences)


def render_psa_trajectory(psa: Optional[Dict]) -> str:
    """'PSA increased from 4.79 ng/mL (December 19, 2025) to 5.55 ng/mL
    (February 2, 2026).'

    Skips the entire section when current_value is null/absent — RCC and
    other non-prostate patients legitimately have no PSA trajectory."""
    if not psa:
        return ""
    current_v = psa.get("current_value")
    if current_v is None:
        return ""
    current_d = _format_date(psa.get("current_date"))
    direction = psa.get("direction", "stable")
    direction_verb = {
        "increased": "has increased",
        "decreased": "has decreased",
        "stable": "remains stable at",
        "fluctuating": "has fluctuated, most recently at",
    }.get(direction, "is")
    if direction in ("stable", "fluctuating"):
        sentence = f"PSA {direction_verb} {current_v} ng/mL ({current_d})."
    elif psa.get("prior_value") is not None:
        prior_v = psa["prior_value"]
        prior_d = _format_date(psa.get("prior_date"))
        sentence = (f"PSA {direction_verb} from {prior_v} ng/mL "
                    f"({prior_d}) to {current_v} ng/mL ({current_d}).")
    else:
        sentence = f"Most recent PSA {current_v} ng/mL ({current_d})."
    # Optional peak context
    if (psa.get("peak_value") is not None
            and psa.get("peak_value") != current_v
            and psa.get("peak_value") != psa.get("prior_value")):
        peak_d = _format_date(psa.get("peak_date"))
        sentence += f" Peak {psa['peak_value']} ng/mL ({peak_d})."
    return sentence


def render_procedure_findings(findings: Optional[List[Dict]]) -> str:
    """Bullet-style sentences for procedure findings, sorted newest first.

    When `finding` is null the renderer emits the procedure date alone
    rather than fabricating a finding clause."""
    if not findings:
        return ""
    def _date_key(f):
        return f.get("date") or "0000"
    sorted_findings = sorted(findings, key=_date_key, reverse=True)
    sentences: List[str] = []
    for pf in sorted_findings:
        proc_label = _PROCEDURE_DISPLAY.get(pf["procedure_type"], pf["procedure_type"])
        date_str = _format_date(pf["date"])
        finding_raw = pf.get("finding")
        if finding_raw and finding_raw.strip():
            finding = finding_raw.strip().rstrip(".")
            sentences.append(f"{proc_label.capitalize()} on {date_str} showed {finding}.")
        else:
            sentences.append(f"{proc_label.capitalize()} on {date_str}.")
    return " ".join(sentences)


def render_current_regimen(regimen: Optional[List[Dict]], sex: str) -> str:
    """List of current urologic medications."""
    if not regimen:
        return ""
    p = _pron(sex)
    items: List[str] = []
    for item in regimen:
        med = item["medication"]
        indication = item.get("indication")
        if indication:
            items.append(f"{med} for {indication}")
        else:
            items.append(med)
    if len(items) == 1:
        return f"{p['sub'].capitalize()} is currently on {items[0]}."
    if len(items) == 2:
        return f"{p['sub'].capitalize()} is currently on {items[0]} and {items[1]}."
    head, tail = items[:-1], items[-1]
    return (f"{p['sub'].capitalize()} is currently on "
            f"{', '.join(head)}, and {tail}.")


def render_interval_status(interval: Optional[Dict], sex: str) -> str:
    """'Since last visit on DATE, ... Patient denies X, Y, Z.'"""
    if not interval:
        return ""
    p = _pron(sex)
    parts: List[str] = []
    if interval.get("summary"):
        parts.append(interval["summary"].rstrip("."))
    if interval.get("denies"):
        denies = interval["denies"]
        if len(denies) == 1:
            parts.append(f"{p['sub'].capitalize()} denies {denies[0]}")
        elif len(denies) == 2:
            parts.append(f"{p['sub'].capitalize()} denies {denies[0]} and {denies[1]}")
        else:
            head, tail = denies[:-1], denies[-1]
            parts.append(f"{p['sub'].capitalize()} denies "
                         f"{', '.join(head)}, and {tail}")
    if not parts:
        return ""
    # Anchor to last visit date if provided
    last_d = interval.get("last_visit_date")
    if last_d:
        joined = ". ".join(parts) + "."
        return f"Since the prior urology visit on {_format_date(last_d)}, {joined.lower()[0]}{joined[1:]}"
    return ". ".join(parts) + "."


def render_today_reason(today_reason: Optional[str]) -> str:
    """Final sentence stating reason for today's visit."""
    if not today_reason or not today_reason.strip():
        return ""
    reason = today_reason.strip().rstrip(".")
    return f"Today's visit is for {reason}."


# ---------------------------------------------------------------------------
# Top-level renderer
# ---------------------------------------------------------------------------

def render_full_hpi(draft: Dict) -> str:
    """Render a validated HPIDraft into a complete HPI paragraph.

    Order of sections (clinically conventional):
      1. Intro (name/age/sex/visit reason)
      2. Prior diagnosis
      3. Treatment history (chronological)
      4. PSA trajectory (most current first)
      5. Procedure findings (most recent first)
      6. Interval status (since last visit)
      7. Current regimen
      8. Today's reason for visit
    """
    sex = draft.get("intro", {}).get("sex", "male")
    sections = [
        render_intro(draft.get("intro")),
        render_prior_diagnosis(draft.get("prior_diagnosis"), sex),
        render_treatment_history(draft.get("treatment_history"), sex),
        render_psa_trajectory(draft.get("psa_trajectory")),
        render_procedure_findings(draft.get("procedure_findings")),
        render_interval_status(draft.get("interval_status"), sex),
        render_current_regimen(draft.get("current_regimen"), sex),
        render_today_reason(draft.get("today_reason")),
    ]
    # Drop empty sections, join with single space (one paragraph).
    return " ".join(s for s in sections if s)
