"""
Deterministic HPI renderer.

Takes a schema-validated HPIDraft dict and emits clinical prose via
templates. The renderer is PURE CODE — it cannot invent content,
introduce contradictions, hallucinate values, mismatch pronouns, or
write meta-commentary, because every output sentence is generated by
a function that reads only the validated input.

Renderer guarantees:
  - Every PSA value comes verbatim from draft.psa_trajectory
  - Every treatment claim comes verbatim from draft.treatment_history
  - Sex pronouns derived from draft.intro.sex (deterministic mapping)
  - No "I have followed the rules" / meta-commentary possible
  - No name placeholders (uses draft.intro.name)
  - No mid-sentence truncations (every render fn returns complete sentence)
"""
from __future__ import annotations

import re
from typing import Dict, List, Optional, Any


# ---------------------------------------------------------------------------
# Pronoun mapping
# ---------------------------------------------------------------------------

_PRONOUNS = {
    "male":   {"sub": "he",  "obj": "him", "poss": "his",  "self": "himself"},
    "female": {"sub": "she", "obj": "her", "poss": "her",  "self": "herself"},
}


def _pron(sex: str) -> Dict[str, str]:
    return _PRONOUNS.get(sex, {"sub": "the patient",
                               "obj": "the patient",
                               "poss": "the patient's",
                               "self": "themselves"})


# ---------------------------------------------------------------------------
# Date formatter
# ---------------------------------------------------------------------------

_MONTH_NAMES = ["", "January", "February", "March", "April", "May",
                "June", "July", "August", "September", "October",
                "November", "December"]


def _format_date(date_str: Optional[str]) -> str:
    """Render YYYY-MM-DD / YYYY-MM / YYYY as 'Month DD, YYYY' / 'Month YYYY' / 'YYYY'."""
    if not date_str:
        return ""
    parts = date_str.split("-")
    try:
        if len(parts) == 1:
            return parts[0]
        if len(parts) == 2:
            return f"{_MONTH_NAMES[int(parts[1])]} {parts[0]}"
        if len(parts) == 3:
            return f"{_MONTH_NAMES[int(parts[1])]} {int(parts[2])}, {parts[0]}"
    except (ValueError, IndexError):
        return date_str
    return date_str


def _date_preposition(date_str: Optional[str]) -> str:
    """Return 'on' for a specific YYYY-MM-DD, 'in' for YYYY or YYYY-MM.

    The grammar of "diagnosed in 2015" vs "diagnosed on January 7, 2026"
    matters — using "in" for a fully specified date reads as a
    template-leak."""
    if not date_str:
        return "in"
    return "on" if date_str.count("-") == 2 else "in"


# ---------------------------------------------------------------------------
# Treatment modality display labels
# ---------------------------------------------------------------------------

_MODALITY_DISPLAY = {
    "prostatectomy": "radical prostatectomy",
    "radiation": "radiation therapy",
    "brachytherapy": "brachytherapy",
    "focal-therapy": "focal therapy",
    "active-surveillance": "active surveillance",
    "ADT": "androgen deprivation therapy",
    "chemotherapy": "chemotherapy",
    "immunotherapy": "immunotherapy",
    "TURP": "TURP",
    "TURBT": "TURBT",
    "nephrectomy": "nephrectomy",
    "cystectomy": "cystectomy",
    "ureteroscopy": "ureteroscopy",
    "shock-wave-lithotripsy": "shock wave lithotripsy",
    "PCNL": "percutaneous nephrolithotomy",
    "orchiectomy": "orchiectomy",
    "varicocelectomy": "varicocelectomy",
    "hydrocelectomy": "hydrocelectomy",
    "cystoscopy-with-treatment": "cystoscopy with treatment",
}

_STATUS_VERB = {
    "completed":   "completed",
    "ongoing":     "is currently undergoing",
    "discontinued": "discontinued",
    "declined":    "declined",
    "scheduled":   "is scheduled for",
}

_PROCEDURE_DISPLAY = {
    "biopsy": "biopsy",
    "cystoscopy": "cystoscopy",
    "urodynamics": "urodynamic study",
    "mri": "MRI",
    "ct": "CT",
    "ultrasound": "ultrasound",
    "psma-pet": "PSMA PET",
    "bone-scan": "bone scan",
    "dexa": "DEXA scan",
    "iv-pyelogram": "IV pyelogram",
    "retrograde-pyelogram": "retrograde pyelogram",
    "voiding-cystogram": "voiding cystogram",
}


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------

def render_intro(intro: Optional[Dict]) -> str:
    """First sentence: '{Name} is a {age}-year-old {sex} who returns for {reason}.'"""
    if not intro:
        return ""
    visit_verb = {
        "follow-up": "returns for",
        "consult": "presents for urology consultation for",
        "new-patient": "is a new urology patient seen for",
        "post-op": "returns for post-operative follow-up of",
        "pre-op": "is seen for pre-operative evaluation of",
    }.get(intro.get("visit_type", "follow-up"), "returns for")
    # "an" before age digits whose spoken form starts with a vowel:
    # 8, 11, 18, 80-89 ("an eighty-two-year-old"). Others use "a".
    age = intro['age']
    article = "an" if str(age)[0] in ('8',) or age in (11, 18) else "a"
    return (
        f"{intro['name']} is {article} {age}-year-old "
        f"{intro['sex']} who {visit_verb} {intro['visit_reason']}."
    )


def render_prior_diagnosis(dx: Optional[Dict], sex: str) -> str:
    """'He was diagnosed with X on January 7, 2026 (Gleason 3+3, Grade Group 1).'"""
    if not dx or not dx.get("primary_dx"):
        return ""
    p = _pron(sex)
    parts = [f"{p['sub'].capitalize()} was diagnosed with {dx['primary_dx']}"]
    if dx.get("dx_date"):
        parts.append(f"{_date_preposition(dx['dx_date'])} "
                     f"{_format_date(dx['dx_date'])}")
    qualifier_parts = []
    if dx.get("gleason"):
        gg = dx.get("grade_group")
        if gg:
            qualifier_parts.append(f"Gleason {dx['gleason']}, Grade Group {gg}")
        else:
            qualifier_parts.append(f"Gleason {dx['gleason']}")
    elif dx.get("grade_group"):
        qualifier_parts.append(f"Grade Group {dx['grade_group']}")
    # Filter literal "null" / "none" strings emitted by the LLM when
    # risk_category is unknown — they leak as "null risk" otherwise.
    risk = dx.get("risk_category")
    if risk and isinstance(risk, str) and risk.strip().lower() not in ("null", "none", "unknown", "n/a", ""):
        qualifier_parts.append(f"{risk} risk")
    if qualifier_parts:
        parts.append(f"({'; '.join(qualifier_parts)})")
    return " ".join(parts) + "."


# A narrative_note that restates the treatment (verb-first) rather than adding
# new context — dropped so it doesn't echo the main clause.
_RESTATEMENT_NOTE_RE = re.compile(
    r"^(?:completed?|complete|started|starting|initiated?|began|underwent|"
    r"received|declined?|ongoing|continuing|most\s+recent|performed|"
    r"status\s+post|s/p|treated\s+with)\b",
    re.IGNORECASE,
)


def render_treatment_history(events: Optional[List[Dict]], sex: str) -> str:
    """Chronological list of treatment events. One sentence per event."""
    if not events:
        return ""
    p = _pron(sex)
    sentences: List[str] = []
    # Sort by date if available (oldest first for chronology)
    def _date_key(e):
        return e.get("date") or "9999"
    sorted_events = sorted(events, key=_date_key)
    for evt in sorted_events:
        modality_label = _MODALITY_DISPLAY.get(evt["modality"], evt["modality"])
        status_verb = _STATUS_VERB.get(evt["status"], evt["status"])
        date_part = ""
        if evt.get("date"):
            date_part = f" {_date_preposition(evt['date'])} {_format_date(evt['date'])}"
        if evt["status"] == "completed":
            sentence = f"{p['sub'].capitalize()} completed {modality_label}{date_part}."
        elif evt["status"] == "ongoing":
            if evt["modality"] == "active-surveillance":
                sentence = (f"{p['sub'].capitalize()} has been managed with "
                            f"active surveillance{date_part}.")
            else:
                if date_part:
                    started_part = f" started{date_part}"
                else:
                    started_part = ""
                sentence = (f"{p['sub'].capitalize()} {status_verb} "
                            f"{modality_label}{started_part}.")
        elif evt["status"] == "discontinued":
            sentence = (f"{p['sub'].capitalize()} previously received "
                        f"{modality_label}{date_part}, since discontinued.")
        elif evt["status"] == "declined":
            sentence = f"{p['sub'].capitalize()} declined {modality_label}."
        elif evt["status"] == "scheduled":
            sentence = (f"{p['sub'].capitalize()} {status_verb} "
                        f"{modality_label}{date_part}.")
        else:
            sentence = (f"{p['sub'].capitalize()} {status_verb} "
                        f"{modality_label}{date_part}.")
        # Append optional narrative note — but only when it adds NEW context,
        # not when it merely restates the treatment already in the sentence
        # ("completed ADT in July 2023" on a completed-ADT event, "most recent
        # TURBT on 05/12/2026"). A restatement starts with a status/treatment
        # verb; a genuine note starts with for/with/at/due-to/etc.
        note = evt.get("narrative_note")
        if note and not _RESTATEMENT_NOTE_RE.match(note.strip()):
            sentence = sentence.rstrip(".") + f" — {note}."
        sentences.append(sentence)
    return " ".join(sentences)


def render_psa_trajectory(psa: Optional[Dict]) -> str:
    """'PSA increased from 4.79 ng/mL (December 19, 2025) to 5.55 ng/mL
    (February 2, 2026).'

    Skips the entire section when current_value is null/absent — RCC and
    other non-prostate patients legitimately have no PSA trajectory."""
    if not psa:
        return ""
    current_v = psa.get("current_value")
    if current_v is None:
        return ""
    current_d = _format_date(psa.get("current_date"))
    direction = psa.get("direction", "stable")
    direction_verb = {
        "increased": "has increased",
        "decreased": "has decreased",
        "stable": "remains stable at",
        "fluctuating": "has fluctuated, most recently at",
    }.get(direction, "is")
    has_prior = psa.get("prior_value") is not None
    if not has_prior:
        # Only one PSA value — a direction word ("remains stable",
        # "increased") falsely implies a comparison and contradicts the
        # Assessment (HOLES: HPI "remains stable at 93.36" vs Assessment
        # "markedly elevated"). State the value without a trend.
        sentence = f"Most recent PSA {current_v} ng/mL ({current_d})."
    elif direction in ("stable", "fluctuating"):
        sentence = f"PSA {direction_verb} {current_v} ng/mL ({current_d})."
    else:
        prior_v = psa["prior_value"]
        prior_d = _format_date(psa.get("prior_date"))
        sentence = (f"PSA {direction_verb} from {prior_v} ng/mL "
                    f"({prior_d}) to {current_v} ng/mL ({current_d}).")
    # Optional peak context — only when the peak is meaningfully HIGHER than
    # the values already stated. A peak equal to (or below) current/prior is
    # redundant noise ("stable at 0.19 ... Peak 0.19"); the LLM sometimes
    # picks such a peak, so require strictly greater.
    peak_v = psa.get("peak_value")
    prior_v = psa.get("prior_value")
    if (peak_v is not None
            and isinstance(peak_v, (int, float))
            and peak_v > current_v
            and (prior_v is None or peak_v > prior_v)):
        peak_d = _format_date(psa.get("peak_date"))
        sentence += f" Peak {peak_v} ng/mL ({peak_d})."
    return sentence


def render_procedure_findings(findings: Optional[List[Dict]]) -> str:
    """Bullet-style sentences for procedure findings, sorted newest first.

    When `finding` is null the renderer emits the procedure date alone
    rather than fabricating a finding clause."""
    if not findings:
        return ""
    def _date_key(f):
        return f.get("date") or "0000"
    sorted_findings = sorted(findings, key=_date_key, reverse=True)
    sentences: List[str] = []
    for pf in sorted_findings:
        proc_label = _PROCEDURE_DISPLAY.get(pf["procedure_type"], pf["procedure_type"])
        date_str = _format_date(pf["date"])
        finding_raw = pf.get("finding")
        if finding_raw and finding_raw.strip():
            finding = finding_raw.strip().rstrip(".")
            sentences.append(f"{proc_label.capitalize()} on {date_str} showed {finding}.")
        else:
            sentences.append(f"{proc_label.capitalize()} on {date_str}.")
    return " ".join(sentences)


def render_current_regimen(regimen: Optional[List[Dict]], sex: str) -> str:
    """List of current urologic medications."""
    if not regimen:
        return ""
    p = _pron(sex)
    items: List[str] = []
    for item in regimen:
        med = item["medication"]
        indication = item.get("indication")
        if indication:
            items.append(f"{med} for {indication}")
        else:
            items.append(med)
    if len(items) == 1:
        return f"{p['sub'].capitalize()} is currently on {items[0]}."
    if len(items) == 2:
        return f"{p['sub'].capitalize()} is currently on {items[0]} and {items[1]}."
    head, tail = items[:-1], items[-1]
    return (f"{p['sub'].capitalize()} is currently on "
            f"{', '.join(head)}, and {tail}.")


# A redundant interval lead-in the LLM prefixes onto the summary, e.g.
# "since the visit on 2026-01-12," / "since the last urology visit,". The
# renderer supplies its own "Since the prior urology visit on DATE," so this
# is stripped to avoid doubling.
_INTERVAL_LEADIN_RE = re.compile(
    # The renderer supplies its own "Since the prior urology visit on DATE,"
    # anchor, so strip a redundant lead-in the LLM prefixes referring back to
    # that prior encounter. Covers the noun the LLM varies on (visit /
    # evaluation / encounter / appointment / assessment / consult[ation] /
    # clinic visit) with the date before OR after it, and REQUIRES the
    # trailing comma so it only removes the lead-in clause — never a
    # legitimate "...follow-up visit was uneventful" mid-summary.
    r"^since\b[^.\n]{0,45}?\b(?:visit|evaluation|encounter|appointment|"
    r"assessment|consult(?:ation)?)\b(?:\s+on\s+[^,.\n]{0,25})?\s*,\s*",
    re.IGNORECASE,
)
# ISO dates that occasionally leak into free-text summary/denies fields.
_ISO_DATE_RE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")

# A word echoed across "for"/"of" ("evaluation for evaluation", "management
# of management") — collapse to a single occurrence. Same word both sides so
# distinct phrases ("side of head") are untouched.
_WORD_ECHO_RE = re.compile(r"\b(\w+)\s+(?:for|of)\s+\1\b", re.IGNORECASE)


def render_interval_status(interval: Optional[Dict], sex: str) -> str:
    """'Since last visit on DATE, ... Patient denies X, Y, Z.'"""
    if not interval:
        return ""
    p = _pron(sex)
    parts: List[str] = []
    last_d = interval.get("last_visit_date")
    if interval.get("summary"):
        s = interval["summary"].rstrip(".")
        # When we supply our own "Since the prior visit on DATE," lead-in
        # below, strip a redundant one the LLM prefixed onto the summary
        # (avoids "Since the prior urology visit on Jan 12, 2026, since the
        # visit on 2026-01-12, ...").
        if last_d:
            s = _INTERVAL_LEADIN_RE.sub("", s).strip()
        # Humanize any leaked ISO dates (2026-01-12 -> January 12, 2026).
        s = _ISO_DATE_RE.sub(lambda m: _format_date(m.group(0)), s)
        if s:
            parts.append(s)
    if interval.get("denies"):
        denies = interval["denies"]
        if len(denies) == 1:
            parts.append(f"{p['sub'].capitalize()} denies {denies[0]}")
        elif len(denies) == 2:
            parts.append(f"{p['sub'].capitalize()} denies {denies[0]} and {denies[1]}")
        else:
            head, tail = denies[:-1], denies[-1]
            parts.append(f"{p['sub'].capitalize()} denies "
                         f"{', '.join(head)}, and {tail}")
    if not parts:
        return ""
    # Anchor to last visit date if provided
    if last_d:
        joined = ". ".join(parts) + "."
        # Lowercase the first letter so it flows after "..., " — but NOT when
        # the first word is an acronym (PSA, CT, MRI) or the summary would be
        # mangled ("pSA has risen").
        first_word = joined.split(" ", 1)[0]
        if not (len(first_word) >= 2 and first_word[:2].isupper()):
            joined = joined[0].lower() + joined[1:]
        return f"Since the prior urology visit on {_format_date(last_d)}, {joined}"
    return ". ".join(parts) + "."


# Lead-in phrases the LLM commonly prefixes onto today_reason. Stripped so
# the rendered "Today's visit is for ..." sentence doesn't double up into
# "Today's visit is for The patient presents for ...".
_TODAY_REASON_LEADIN_RE = re.compile(
    r"^(?:the\s+patient\s+|he\s+|she\s+|patient\s+)?"
    r"(?:presents?|is\s+here|is\s+seen|returns?|comes?\s+in|is\s+being\s+seen)"
    r"(?:\s+today)?\s+(?:for|to|with)\s+",
    re.IGNORECASE,
)


def render_today_reason(today_reason: Optional[str]) -> str:
    """Final sentence stating reason for today's visit."""
    if not today_reason or not today_reason.strip():
        return ""
    reason = today_reason.strip().rstrip(".")
    # Drop a redundant "The patient presents for"/"returns for"/etc. lead-in
    # so it doesn't concatenate with our "Today's visit is for" stem.
    reason = _TODAY_REASON_LEADIN_RE.sub("", reason).strip()
    # Also drop a bare leading "for " left after partial matches.
    reason = re.sub(r"^for\s+", "", reason, flags=re.IGNORECASE).strip()
    if not reason:
        return ""
    return f"Today's visit is for {reason}."


# ---------------------------------------------------------------------------
# Top-level renderer
# ---------------------------------------------------------------------------

def render_full_hpi(draft: Dict) -> str:
    """Render a validated HPIDraft into a complete HPI paragraph.

    Order of sections (clinically conventional):
      1. Intro (name/age/sex/visit reason)
      2. Prior diagnosis
      3. Treatment history (chronological)
      4. PSA trajectory (most current first)
      5. Procedure findings (most recent first)
      6. Interval status (since last visit)
      7. Current regimen
      8. Today's reason for visit
    """
    sex = draft.get("intro", {}).get("sex", "male")
    sections = [
        render_intro(draft.get("intro")),
        render_prior_diagnosis(draft.get("prior_diagnosis"), sex),
        render_treatment_history(draft.get("treatment_history"), sex),
        render_psa_trajectory(draft.get("psa_trajectory")),
        render_procedure_findings(draft.get("procedure_findings")),
        render_interval_status(draft.get("interval_status"), sex),
        render_current_regimen(draft.get("current_regimen"), sex),
        render_today_reason(draft.get("today_reason")),
    ]
    # Drop empty sections, join with single space (one paragraph).
    text = " ".join(s for s in sections if s)
    # Cross-specialty referral scrubber — even templated v2 text can
    # carry a stray "by urology" if the LLM emitted it in a free-string
    # field like visit_reason / today_reason / narrative_note.
    from .history_cleaners import strip_urology_referral_framing
    text = strip_urology_referral_framing(text)
    # Collapse a word echoed across a preposition, e.g. "urology consultation
    # for evaluation of ..." becomes "urologic evaluation for evaluation of ..."
    # after the referral scrub — reduce "evaluation for evaluation" to a single
    # "evaluation". Same word on both sides only, so distinct phrases are safe.
    text = _WORD_ECHO_RE.sub(r"\1", text)
    return text
